# before committing check this file here: https://lint.travis-ci.org/

language: python

# travis-ci runs by default on ancient Ubuntu 12.04 (precise)
# following options will give us Ubuntu 14.04 (trusty)
sudo: true
dist: trusty

# testing pyqt5 apps require X server
addons:
  apt:
    packages:
    - xvfb
    - xfonts-100dpi
    - xfonts-75dpi
    - xorg
    - dbus-x11

matrix:
    include:
        - os: linux
          python: 3.6
          env: TOXENV=packaging
        - os: linux
          python: 3.5
          env: TOXENV=py35
        - os: linux
          python: 3.6
          env: TOXENV=py36
        - os: linux
          python: 3.6-dev
          env: TOXENV=py36
        - os: linux
          python: nightly
          env: TOXENV=py37
        - os: linux
          python: 3.6
          env: TOXENV=coverage
#    uncomment and adjust if you want to allow some failures
    allow_failures:
        - os: linux
          python: nightly
          env: TOXENV=py37


script:
  - sudo apt-get update
  - sudo apt-get install xfonts-cyrillic -y # TODO should be move to apt addons
  - pip install -r requirements.txt --upgrade
  - pip install -r tests/requirements-test.txt --upgrade
  - tox --recreate --notest && tox
  - if [[ "$TRAVIS_TEST_RESULT" == "0" ]] && [[ $TOXENV == "packaging" ]]; then .travis/deploy_package.sh "$TARGET" $PRECMD; fi

